# Generated by Django 5.1.1 on 2024-09-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('tipoIdentificacion', models.CharField(choices=[('CC', 'CEDULA'), ('TI', 'TARJETA IDENTIDAD'), ('CE', 'CEDULA EXTRANJERIA'), ('RC', 'REGISTRO CIVIL')], max_length=2)),
                ('fechaNacimiento', models.DateField()),
                ('numeroCelular', models.CharField(max_length=20)),
                ('correoElectronico', models.EmailField(max_length=80)),
            ],
        ),
    ]
