# Generated by Django 5.1.1 on 2024-09-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Internet 200 MB', 'Internet 200 MB'), ('Internet 400 MB', 'Internet 400 MB'), ('Internet 600 MB', 'Internet 600 MB'), ('Directv Go', 'Directv Go'), ('Paramount+', 'Paramount+'), ('Win+', 'Win+')], max_length=80)),
                ('fechaInicio', models.DateField()),
                ('ultimaFacturacion', models.DateField()),
                ('ultimoPago', models.IntegerField(default=0)),
                ('identificacionCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='clientes.cliente')),
            ],
            options={
                'unique_together': {('identificacionCliente', 'servicio')},
            },
        ),
    ]
