# Generated by Django 5.1.1 on 2024-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(choices=[('1', 'Internet 200 MB'), ('2', 'Internet 400 MB'), ('3', 'Internet 600 MB'), ('4', 'Directv Go'), ('5', 'Paramount+'), ('6', 'Win+')], max_length=80),
        ),
    ]
